package partner_test

const (
	TestOfferJSON = `
{
    "offerTypeId": "microsoft-azure-virtualmachines",
    "publisherId": "publisherId",
    "status": "neverPublished",
    "pcMigrationStatus": "none",
    "isvUpgradeRequest": false,
    "version": 6,
    "id": "test",
    "definition": {
        "displayText": "Test offer",
        "offer": {
            "microsoft-azure-virtualmachines.gtmMaterials": "gtmMaterials",
            "microsoft-azure-virtualmachines.managerContactName": "managerContactName",
            "microsoft-azure-virtualmachines.managerContactEmail": "managerContactEmail",
            "microsoft-azure-virtualmachines.managerContactPhone": "managerContactPhone",
            "microsoft-azure-marketplace-testdrive.enabled": false,
            "microsoft-azure-marketplace-testdrive.videos": [],
            "microsoft-azure-marketplace.title": "title",
            "microsoft-azure-marketplace.summary": "summary",
            "microsoft-azure-marketplace.longSummary": "longSummary",
            "microsoft-azure-marketplace.description": "description",
            "microsoft-azure-marketplace.cspOfferOptIn": false,
            "microsoft-azure-marketplace.offerMarketingUrlIdentifier": "offerMarketingUrlIdentifier",
            "microsoft-azure-marketplace.allowedSubscriptions": [
                "2232470c-76f3-455c-8a62-1e37a6c38d9d",
                "6fd72683-31fa-4409-9ea3-dbb25aacc9ea"
            ],
            "microsoft-azure-marketplace.usefulLinks": [],
            "microsoft-azure-marketplace.categories": [
                "devService"
            ],
            "microsoft-azure-marketplace.smallLogo": "smallLogo",
            "microsoft-azure-marketplace.mediumLogo": "mediumLogo",
            "microsoft-azure-marketplace.largeLogo": "largeLogo",
            "microsoft-azure-marketplace.wideLogo": "wideLogo",
            "microsoft-azure-marketplace.screenshots": [],
            "microsoft-azure-marketplace.videos": [],
            "microsoft-azure-marketplace.leadDestination": "None",
            "microsoft-azure-marketplace.tableLeadConfiguration": {},
            "microsoft-azure-marketplace.blobLeadConfiguration": {},
            "microsoft-azure-marketplace.salesForceLeadConfiguration": {},
            "microsoft-azure-marketplace.crmLeadConfiguration": {},
            "microsoft-azure-marketplace.httpsEndpointLeadConfiguration": {},
            "microsoft-azure-marketplace.marketoLeadConfiguration": {},
            "microsoft-azure-marketplace.privacyURL": "privacyURL",
            "microsoft-azure-marketplace.useEnterpriseContract": false,
            "microsoft-azure-marketplace.termsOfUse": "https://github.com/cncf/foundation/blob/master/copyright-notices.md",
            "microsoft-azure-marketplace.customAmendments": {},
            "microsoft-azure-marketplace.engineeringContactName": "engineeringContactName",
            "microsoft-azure-marketplace.engineeringContactEmail": "engineeringContactEmail",
            "microsoft-azure-marketplace.engineeringContactPhone": "engineeringContactPhone",
            "microsoft-azure-marketplace.supportContactName": "supportContactName",
            "microsoft-azure-marketplace.supportContactEmail": "supportContactEmail",
            "microsoft-azure-marketplace.supportContactPhone": "supportContactPhone",
            "microsoft-azure-marketplace.publicAzureSupportUrl": "publicAzureSupportUrl",
            "microsoft-azure-marketplace.fairfaxSupportUrl": "fairfaxSupportUrl"
        },
        "plans": [
            {
                "planId": "planId",
                "microsoft-azure-virtualmachines.skuTitle": "skuTitle",
                "microsoft-azure-virtualmachines.skuSummary": "skuSummary",
                "microsoft-azure-virtualmachines.skuDescription": "skuDescription",
                "microsoft-azure-virtualmachines.hideSKUForSolutionTemplate": true,
                "microsoft-azure-virtualmachines.cloudAvailability": [
                    "PublicAzure"
                ],
                "microsoft-azure-virtualmachines.certificationsFairfax": [],
                "microsoft-azure-virtualmachines.supportsAcceleratedNetworking": false,
                "regions": [
                    "AF",
                    "AL",
                    "DZ",
                    "AD",
                    "AO",
                    "AR",
                    "AU",
                    "AZ",
                    "BH",
                    "BD",
                    "BB",
                    "BZ",
                    "BM",
                    "BO",
                    "BA",
                    "BW",
                    "BN",
                    "CV",
                    "CM",
                    "KY",
                    "CL",
                    "CN",
                    "CO",
                    "CR",
                    "CI",
                    "CW",
                    "DO",
                    "EC",
                    "EG",
                    "SV",
                    "ET",
                    "FO",
                    "FJ",
                    "GE",
                    "GH",
                    "GT",
                    "HN",
                    "HK",
                    "IS",
                    "ID",
                    "IQ",
                    "IL",
                    "JM",
                    "JP",
                    "JO",
                    "KZ",
                    "KE",
                    "KW",
                    "KG",
                    "LB",
                    "LY",
                    "MO",
                    "MK",
                    "MY",
                    "MU",
                    "MX",
                    "MD",
                    "MN",
                    "ME",
                    "MA",
                    "NA",
                    "NP",
                    "NI",
                    "NG",
                    "OM",
                    "PK",
                    "PS",
                    "PA",
                    "PY",
                    "PE",
                    "PH",
                    "QA",
                    "RW",
                    "KN",
                    "SN",
                    "SG",
                    "SI",
                    "LK",
                    "TJ",
                    "TZ",
                    "TH",
                    "TT",
                    "TN",
                    "TM",
                    "UG",
                    "UA",
                    "UY",
                    "UZ",
                    "VA",
                    "VE",
                    "VN",
                    "VI",
                    "YE",
                    "ZM",
                    "ZW",
                    "AM",
                    "AT",
                    "BY",
                    "BE",
                    "BR",
                    "BG",
                    "CA",
                    "HR",
                    "CY",
                    "CZ",
                    "DK",
                    "EE",
                    "FI",
                    "FR",
                    "DE",
                    "GR",
                    "HU",
                    "IN",
                    "IE",
                    "IT",
                    "KR",
                    "LV",
                    "LI",
                    "LT",
                    "LU",
                    "MT",
                    "MC",
                    "NL",
                    "NZ",
                    "NO",
                    "PL",
                    "PT",
                    "PR",
                    "RO",
                    "RU",
                    "SA",
                    "RS",
                    "SK",
                    "ZA",
                    "ES",
                    "SE",
                    "CH",
                    "TW",
                    "TR",
                    "AE",
                    "GB",
                    "US"
                ],
                "virtualMachinePricing": {
                    "isByol": true,
                    "freeTrialDurationInMonths": 0
                },
                "virtualMachinePricingV2": {
                    "isByol": true,
                    "freeTrialDurationInMonths": 0
                },
                "microsoft-azure-virtualmachines.operatingSystemFamily": "operatingSystemFamily",
                "microsoft-azure-virtualmachines.osType": "osType",
                "microsoft-azure-virtualmachines.operationSystem": "operationSystem",
                "microsoft-azure-virtualmachines.recommendedVMSizes": [
                    "ds2-standard-v2",
                    "d2-standard-v3",
                    "d2s-standard-v3"
                ],
                "microsoft-azure-virtualmachines.openPorts": [],
                "microsoft-azure-virtualmachines.vmImages": {
                    "2019.10.11": {
                        "osVhdUrl": "osVhdUrl",
                        "lunVhdDetails": []
                    },
					"2019.10.12": {
                        "osVhdUrl": "osVhdUrl",
                        "lunVhdDetails": []
                    }
                }
            }
        ]
    },
    "changedTime": "2019-10-11T17:46:59.0543751Z"
}
`
)
